### ISSUE TITLE
Decoding actions and not observations

### ISSUE THREAD

**Issue by Soha18** [tianyudwang/LAPAL#1]
Hi,

Thanks for providing an open implementation with clean codes.

I just want to ask why did you choose VAE to encode and decode actions (it is already small vector, 8 or 7 for example) and not observations which are higher dimension (42 or more depends on the env and task)?
 
Stable-baselines3 provides GAIL implementation in "imitation learning" branch, is it possible to apply your idea with it? 

thanks in advance.
kind regards

**Comment by tianyudwang** [comment]
> Hi,
> 
> Thanks for providing an open implementation with clean codes.
> 
> I just want to ask why did you choose VAE to encode and decode actions (it is already small vector, 8 or 7 for example) and not observations which are higher dimension (42 or more depends on the env and task)?
> 
> Stable-baselines3 provides GAIL implementation in "imitation learning" branch, is it possible to apply your idea with it?
> 
> thanks in advance. kind regards

Thank you for interest. We believe it is equally important to compress the states as the actions, and we are working on an extended version which considers both. Our motivation on learning latent actions is from the example of controlling the robot arm joints (7 dof) versus controlling in its end-effector. In fact, [this paper](https://arxiv.org/abs/1909.09674) shows that we only need 2 dof, which makes it easier to understand and interpolate the robot behavior.

The imitation learning library from SB3 is a good starting point but we have personally found its implementation to be quite convoluted. We also found discriminator regularization tricks (gradient penalty, spectral normalization) to be quite important in the robosuite environments and it would be just easier for us to implement our own version. It would definitely be possible to apply the latent space ideas on top of the imitation learning library.
