### ISSUE TITLE
Episode mean reward is too low and poor performance

### ISSUE THREAD

**Issue by Soha18** [tianyudwang/LAPAL#3]
Hi,

Thanks for this implementation..
I utilized before LAPAL-main to train GAIL agent with human dataset in robosuite environment and the results were relatively good for some tasks, but when I tried LAPAL-robosuite branch the result was so bad and the agent could not learn at all. the plots of disc seems good enough but the evaluation and rollouts are so bad just like the agent perform completely random actions.
I may missed something .. would you please advice!!

I tried with three tasks and different datasets but the same result..

Thanks in advance

**Comment by tianyudwang** [comment]
Hi, 

The main branch is the implementation of the [LAPAL preprint](https://arxiv.org/abs/2206.11299). The other branches are experimental code for other projects and will be removed in the future. Sorry for the confusion.
